# tomcat 启动端口号
server:
  port: 8082

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        prefetch: 2 # 每次签收个数
        acknowledge-mode: manual  # 手动签收


